In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR  # Import SVR
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv("/content/Maternal Health Risk Data Set.csv")

In [3]:
df.head()

Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0      98.0         86  high risk
1   35         140           90  13.0      98.0         70  high risk
2   29          90           70   8.0     100.0         80  high risk
3   30         140           85   7.0      98.0         70  high risk
4   35         120           60   6.1      98.0         76   low risk

In [4]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [5]:
print(X)

[[ 25. 130.  80.  15.  98.  86.]
 [ 35. 140.  90.  13.  98.  70.]
 [ 29.  90.  70.   8. 100.  80.]
 ...
 [ 35.  85.  60.  19.  98.  86.]
 [ 43. 120.  90.  18.  98.  70.]
 [ 32. 120.  65.   6. 101.  76.]]


In [6]:
print(y)

['high risk' 'high risk' 'high risk' ... 'high risk' 'high risk'
 'mid risk']


In [10]:
label_map = {'low risk': 0, 'mid risk': 1, 'high risk': 2}
y_numeric = np.array([label_map[val] for val in y])
print(y_numeric)

[2 2 2 ... 2 2 1]


In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y_numeric, test_size=0.1, random_state=0)
column_means = np.nanmean(X_train, axis=0)
X_train_filled = np.where(np.isnan(X_train), column_means, X_train)
X_test_filled = np.where(np.isnan(X_test), column_means, X_test)
print (X_test)

[[ 23.   120.    90.     7.5   98.    70.  ]
 [ 23.   130.    70.     6.9   98.    70.  ]
 [ 35.   100.    70.     7.5   98.    66.  ]
 [ 22.   100.    65.    12.    98.    80.  ]
 [ 13.    90.    65.     7.8  101.    80.  ]
 [ 35.   140.    90.    13.    98.    70.  ]
 [ 25.   120.    90.    12.   101.    80.  ]
 [ 25.   140.   100.     7.01  98.    80.  ]
 [ 22.   100.    65.     7.2   98.    70.  ]
 [ 60.    90.    65.     7.9   98.    77.  ]
 [ 15.    76.    49.     7.8   98.    77.  ]
 [ 19.   120.    80.     7.    98.    70.  ]
 [ 32.   120.    90.     7.5   98.    70.  ]
 [ 18.    90.    60.     6.9   98.    70.  ]
 [ 17.    85.    60.     7.9  102.    86.  ]
 [ 32.   120.    90.     6.8   98.    70.  ]
 [ 60.    90.    65.     6.8   98.    77.  ]
 [ 25.   140.   100.     6.8   98.    80.  ]
 [ 25.   140.   100.     7.5   98.    80.  ]
 [ 42.   120.    80.     7.5   98.    70.  ]
 [ 20.   120.    75.     7.01 100.    70.  ]
 [ 20.   100.    90.     7.5   98.    88.  ]
 [ 35.   1

In [16]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_filled)
X_test_scaled = scaler.transform(X_test_filled)

# Initialize and fit the SVR model
svr = SVR()

svr.fit(X_train_scaled, y_train)

# Predictions
y_pred = svr.predict(X_test_scaled)
y_pred_rounded = np.round(y_pred).astype(int)
print(y_pred_rounded)

[0 1 0 1 1 2 2 2 0 0 0 0 0 0 1 0 0 2 2 0 1 0 1 2 0 0 1 1 0 0 1 2 0 2 1 0 2
 0 2 1 0 0 0 0 1 0 2 0 0 0 0 0 2 1 1 1 1 2 0 1 0 2 2 0 2 0 0 0 2 0 1 1 1 0
 1 0 0 0 1 0 1 1 0 0 1 2 0 1 0 2 0 2 1 1 2 0 2 1 1 2 2 2]


In [17]:
accuracy = np.mean(y_pred_rounded == y_test)
print("Accuracy:", accuracy)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Accuracy: 0.696078431372549
Mean Squared Error: 0.2510215492079501
